<p>
    Check out the latest versions of Vulnero on GitHub or fork your own.
</p>
<p>
    <a href="<?php echo $this->gitHubUrl; ?>" title="Download Vulnero <?php echo $this->version; ?>" class="btn info">Download</a>
    <a href="/installing" title="Installing" class="btn">Quick Start</a>
</p>
<p>
    View the <strong><?php echo $this->version; ?></strong> version <a href="/documentation">documentation</a>.
</p>
